export const USER_STATE_CHANGED = "USER_STATE_CHANGED"
export const USER_POST_STATE_CHANGED = "USER_POST_STATE_CHANGED"
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE"




export const USER_STATE_CHANGED = "USER_STATE_CHANGED"
export const USER_POST_STATE_CHANGED = "USER_POST_STATE_CHANGED"
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE"