export const USER_STATE_CHANGED = "USER_STATE_CHANGED"
export const USER_POST_STATE_CHANGED = "USER_POST_STATE_CHANGED"
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE"




export const USERS_FOLLOWING_STATE_CHANGE = "USERS_FOLLOWING_STATE_CHANGE"
export const USERS_POSTS_STATE_CHANGED = "USERS_POSTS_STATE_CHANGED"
export const USERS_DATA_STATE_CHANGED = "USERS_DATA_STATE_CHANGED"